function [DAModeledEEG, NewWindowLabel,NewWindowGestureLabel] = DA_Modeling (SignalSegment,SegmentLabel, BesselFunctions, WindowLength, ConnectivityMatrix, NetworkMatrix, MovementToModel)

NumberSubSegments=1;
NumberSegments = size(SignalSegment,3);
K=size(SignalSegment,1); %Number channels

for S=1:NumberSegments
   if (SegmentLabel(S)==MovementToModel)
        start_point=1;
        NumberSubGesture=1;

        % weights obtained from Granger causality calculation for Nk
        SegmentConnectivityMatrix=ConnectivityMatrix(:,:,S);
        a=zeros(K,K);
        for k=1:K
            vind = find(NetworkMatrix(:,k));
            for l=vind'
                a(l,k)=SegmentConnectivityMatrix(l,k);
            end
        end
        sumVectorPerColumn=sum(a,1);
        a=a./sumVectorPerColumn;

        LengthSegment = length(SignalSegment(:,:,S));
        while( start_point + WindowLength - 1 <= LengthSegment)
            EEGsignal= SignalSegment(:,start_point:start_point+WindowLength-1,S);
       
            %Initialize Parameters
            mu=0.1; %non-negative step size parameter
            M=7; %represents the length of the window of the signal u_k,i.
            d = BesselFunctions(NumberSubGesture,:); %target
            phi=cell(1,WindowLength+1);
            phi{1,1}=zeros(M,K);

            psi=cell(1,WindowLength+1);
            psi{1,1}=zeros(M,K);
            u=cell(1,WindowLength+1);
        
            i=1;
            while(i + M <= WindowLength) 
                phi{1,i+1}=zeros(M,K); 
                psi{1,i+1}=zeros(M,K);
       
                for k=1:K %each electrode/channel/node
                    u{1,i}(:,k) = EEGsignal(k,i:(i-1)+M);
                    u{1,i+1}(:,k) = EEGsignal(k,i+1:i+M); 

                    %adapt
                    psi{1,i+1}(:,k) = phi{1,i}(:,k) + (mu*(u{1,i+1}(:,k)).')*(d(i+1)-u{1,i+1}(:,k).*phi{1,i}(:,k));
                end
                for k=1:K
                    %combine
                    vind = find(a(:,k)); 
                    for l=vind'
                        phi{1,i+1}(:,k) = phi{1,i+1}(:,l)+a(l,k)*psi{1,i+1}(:,l);
                    end
                    phi{1,i+1}(:,k)=(1/(size(vind,1)-1))*phi{1,i+1}(:,k);
                end
                i=i+1;
            end

            for k=1:K
                for p=1:i
                    meanA(k,p)=mean(phi{1,p}(:,k)); 
                    ConstructedEEGWindowSegment(k,p)=meanA(k,p)*EEGsignal(k,p);
                end
            end
            ConstructedEEGWindowSegment = ConstructedEEGWindowSegment(:,2:end); %in order to avoid the initial 0 column generated by DA
            DAModeledEEG(:,:,NumberSubSegments) = normalize(ConstructedEEGWindowSegment,2);
            %labelled Slidding window
            NewWindowLabel(:,NumberSubSegments)=SegmentLabel(:,S);
            NewWindowGestureLabel(:,:,NumberSubSegments) = NumberSubGesture;

            start_point = start_point + WindowLength;
            NumberSubSegments = NumberSubSegments + 1;
            NumberSubGesture = NumberSubGesture +1;
        end
    end
end

end